# create a data only container to save the
# postgres data
# - don't change the image on this
data:
  image: ubuntu:trusty
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: openmason/fleet-postgis:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

web:
  build: service
  #command: python manage.py runserver 0.0.0.0:80
  command: /usr/local/bin/circusd /etc/circusd.conf
  # Shortcut to load the latest code to container
  volumes:
    - ./service:/deploy
  ports:
    - "80:80"
  links:
    - postgres:postgres
