#db:
  #image: postgres
  #volumes:
    #- /home/vagrant/postgres_data:/var/lib/postgresql

web:
  build: .
  #command: python manage.py runserver 0.0.0.0:80
  command: /usr/local/bin/circusd /etc/circusd.conf
  # Shortcut to load the latest code to container
  volumes:
    - .:/deploy
  ports:
    - "5080:80"
  #links:
    #- db

